services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tdd_agent
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-d",
          "tdd_agent",
        ]
      interval: 10s
      timeout: 10s
      retries: 15

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aueb.gr
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    restart: unless-stopped
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres-data:
  pgadmin-data:
