spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tdd_agent
    username: admin
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
